# Generated by Django 2.1.7 on 2019-06-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_portfoliolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolike',
            name='lol',
            field=models.IntegerField(),
        ),
    ]
