# Generated by Django 2.1.7 on 2019-06-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190606_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolike',
            name='lol',
            field=models.IntegerField(null=True),
        ),
    ]
