"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECTPATH = os.path.dirname(__file__)

DEBUG = __debug__
TEMPLATE_DEBUG = DEBUG

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm41cx)wlxiwt@ao3fuluw$%b8p@$=rxsh+-1y48@2wxg&(pxpl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['52.60.143.249','0.0.0.0','127.0.0.1','localhost', '3ea8ce38.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'portal',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    'allauth',
    'rest_auth',
    'rest_auth.registration',
    'allauth.account',
    'corsheaders',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIAL = True

ROOT_URLCONF = 'core.urls'

TEMPLATE_DIRS = []
# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# using mysql database
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3'
        }
    }
else:
    DATABASES = {
        'default': {
            'STORAGE_ENGINE': 'MyISAM', # used for south InnoDB would recommended
            'ENGINE': 'django.db.backends.mysql',     # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
            'NAME': 'unwravel',               # Or path to database file if using sqlite3.
            'USER': 'root',               # Not used with sqlite3.
            'PASSWORD': 'new-password',                # Not used with sqlite3.
            'HOST': 'localhost',                      # Set to empty string for localhost. Not used with sqlite3.
            'PORT': '',                               # Set to empty string for default. Not used with sqlite3
        }
    }



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'portal.UnwravelUser'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%s',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'COERCE_DECIMAL_TO_STRING': False
}

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_AUTHENTICATION_METHOD = 'email'

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'portal.serializers.UnwravelSignupSerializer',  # noqa
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(PROJECTPATH, 'static')

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(PROJECTPATH, "images"),
]

BRAND_LIST = ["ABCTech", "Ability Systems","Acramatic","ACS","Acu-Rite","Adtech","AeroTech","Aggie Charmilles"
 ,"AH-HA","Alberti","Allen Bradley","Amada","AMC4","Anilam","Anorad","Axyz","B and R","Bandit","Biesse America","Bosch","BostoMatic"
 ,"Brother","Bridgeport","Burny","Camsoft","Centroid","Centurion","CharleyBot","Chmer","Cincinnati","CNC Masters"
 ,"CMS","C-Tek","Daewoo", "Datron","Deckel Maho","DeskCNC","DMG","DynaPath","Dooson","EasiCNC","Edge","Enroute","EMC","Emco"
 ,"EZ","Fadal","Fanuc","FlashCut","Esab","Fagor","GE","Gemini","General Automation","Giddings and Lewis","GSK","Haas"
 ,"Hansvedt","Hardinge","Heinz","Hitachi-Seiki","HPGL","Homag WoodWop","HoneyBee","Hurco","Hust","Hycut","Hypertherm","Hyundai"
 ,"Ingersoll","Koike","Komo","Laguna","Laserdyne","Leading","LightMachines"
 ,"Locshun","Mach 2,3&4 Controllers","Masterwood","Matsura","Maho","Mazak","Milltronics","Mitsubishi","Mori-Seki"
 ,"NC Studio","Nee","Nice","Northwood","Num","OKK","Okuma","OmniTech","OmniTurn","Onsrund","OpenCNC","OSAI","Pacer","Precision"
 ,"Precix","ProLight","RoboTool","Roland","Romero","Sabre","Seib-Meyer","Selexx","Sharanoa","Sherline","Shinx"
 ,"Shoda","ShopBot","ShopSabre","ShopTask","Siemens","SNK","Sodick","Sony","SouthBend","Southwest Industries ProtoTack","Style"
 ,"Taurus","Tecno","Testra","Thermwood","Torchmate","Tormach","Toshiba","Touch","Trumph","Turbo","Turner","Turmaster","Vernon","Vicon"
 ,"Vision","Weihong","WinCNC","WoodPecker","Xilog","Yasnac","Yeager","Zeus"]
MODEL_LIST = [
        "DM-1",
        "DM-2",
        "DT-1",
        "DT-2",
        "EC-1600",
        "EC-1600ZT",
        "EC-400",
        "EC-500",
        "GR-510",
        "GR-712",
        "MINI MILL",
        "Mini Mill 2",
        "OM-2A",
        "Super Mini Mill",
        "Super Mini Mill 2",
        "TM-1",
        "TM-1P",
        "TM-2",
        "TM-2P",
        "TM-3",
        "TM-3P",
        "UMC-750",
        "UMC-750SS",
        "VF-1",
        "VF-10",
        "VF-10/50",
        "VF-11",
        "VF-11/50",
        "VF-1YT",
        "VF-2",
        "VF-2SS",
        "VF-2SS YT",
        "VF-2TR",
        "VF-2YT",
        "VF-3",
        "VF-3S",
        "VF-3SSYT",
        "VF-3YT",
        "VF-3YT/50",
        "VF-4",
        "VF-4SS",
        "VF-5 50XT",
        "VF-5/40",
        "VF-5/40TR",
        "VF-5/40XT",
        "VF-5/50",
        "VF-5/50TR",
        "VF-5SS",
        "VF-6",
        "VF-6/40TR",
        "VF-6/50",
        "VF-6/50TR",
        "VF-6SS",
        "VF-7",
        "VF-7/50",
        "VF-8",
        "VF-8/50",
        "VF-9",
        "VF-9/50",
        "VM-2",
        "VM-3",
        "VM-6",
        "DS-30",
        "DS-30SS",
        "DS-30SSY",
        "DS-30Y",
        "OL-1",
        "ST-10",
        "ST-10Y",
        "ST-15",
        "ST-15Y",
        "ST-20",
        "ST-20SS",
        "ST-20SSY",
        "ST-20Y",
        "ST-25",
        "ST-25Y",
        "ST-30",
        "ST-30SS",
        "ST-30SSY",
        "ST-30Y",
        "ST-35",
        "ST-35Y",
        "ST-40",
        "ST-40L",
        "ST-45",
        "ST-45L",
        "ST-50",
        "ST-55",
        "TL-1",
        "TL-2",
        "TL-3",
        "TL-3B",
        "PUMA 8S"

    ]
MODEL_LIST_AVAILABLE = [
        "DM1",
        "DM2",
        "DT1",
        "DT2",
        "EC1600",
        "EC1600ZT",
        "EC400",
        "EC500",
        "GR510",
        "GR712",
        "MINIMILL",
        "MiniMill2",
        "OM2A",
        "SuperMiniMill",
        "SuperMiniMill2",
        "TM1",
        "TM1P",
        "TM2",
        "TM2P",
        "TM3",
        "TM3P",
        "UMC750",
        "UMC750SS",
        "VF1",
        "VF10",
        "VF10/50",
        "VF11",
        "VF11/50",
        "VF1YT",
        "VF2",
        "VF2SS",
        "VF2SSYT",
        "VF2TR",
        "VF2YT",
        "VF3",
        "VF3SS",
        "VF3SSYT",
        "VF3YT",
        "VF3YT/50",
        "VF4",
        "VF4SS",
        "VF550XT",
        "VF5/40",
        "VF5/40TR",
        "VF5/40XT",
        "VF5/50",
        "VF5/50TR",
        "VF5SS",
        "VF6",
        "VF6/40TR",
        "VF6/50",
        "VF6/50TR",
        "VF6SS",
        "VF7",
        "VF7/50",
        "VF8",
        "VF8/50",
        "VF9",
        "VF9/50",
        "VM2",
        "VM3",
        "VM6",
        "DS30",
        "DS30SS",
        "DS30SSY",
        "DS30Y",
        "OL1",
        "ST10",
        "ST10Y",
        "ST15",
        "ST15Y",
        "ST20",
        "ST20SS",
        "ST20SSY",
        "ST20Y",
        "ST25",
        "ST25Y",
        "ST30",
        "ST30SS",
        "ST30SSY",
        "ST30Y",
        "ST35",
        "ST35Y",
        "ST40",
        "ST40L",
        "ST45",
        "ST45L",
        "ST50",
        "ST55",
        "TL1",
        "TL2",
        "TL3",
        "TL3B",
        "Puma 8S"
    ],
BOOTSTRAP4 = {
    'include_jquery': True,
}
